{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Analyse de Hauteur de Surface de la Mer (SSH) avec U-NET\n",
    "\n",
    "Ce notebook implémente un modèle U-NET léger fonctionnant sur CPU pour analyser des données de hauteur de surface de la mer (SSH).\n",
    "\n",
    "Nous allons couvrir :\n",
    "1. Génération de données SSH synthétiques\n",
    "2. Implémentation du modèle U-NET avec PyTorch Lightning\n",
    "3. Entraînement du modèle\n",
    "4. Inférence sur de nouvelles données\n",
    "5. Visualisation des résultats"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Installation des dépendances"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Installation des packages nécessaires\n",
    "!pip install torch torchvision pytorch-lightning matplotlib numpy seaborn"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Importation des bibliothèques"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "import os\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import pytorch_lightning as pl\n",
    "from pytorch_lightning.callbacks import ModelCheckpoint, EarlyStopping\n",
    "\n",
    "# Configuration pour utiliser CPU\n",
    "os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"\"\n",
    "device = torch.device('cpu')\n",
    "\n",
    "# Configuration matplotlib pour de plus belles visualisations\n",
    "plt.style.use('seaborn-v0_8-whitegrid')\n",
    "sns.set_context(\"notebook\", font_scale=1.2)\n",
    "\n",
    "# Vérifier l'utilisation du CPU\n",
    "print(f\"Utilisation du périphérique: {device}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Génération de données SSH synthétiques\n",
    "\n",
    "Nous allons créer un dataset synthétique qui imite les motifs de hauteur de surface de la mer, avec :\n",
    "- Des ondes de base (représentant des courants)\n",
    "- Des tourbillons (eddies) aléatoires\n",
    "- Du bruit pour simuler des perturbations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "class LightSSHDataset(Dataset):\n",
    "    \"\"\"Dataset SSH synthétique léger pour tests sans GPU\"\"\"\n",
    "    def __init__(self, num_samples=100, size=64, noise_level=0.05, is_train=True):\n",
    "        \"\"\"\n",
    "        Args:\n",
    "            num_samples: Nombre d'échantillons à générer\n",
    "            size: Taille des images (size x size)\n",
    "            noise_level: Niveau de bruit à ajouter\n",
    "            is_train: Si True, génère les données d'entrée avec du bruit\n",
    "        \"\"\"\n",
    "        self.size = size\n",
    "        self.num_samples = num_samples\n",
    "        self.noise_level = noise_level\n",
    "        self.is_train = is_train\n",
    "        self.clean_data, self.noisy_data = self._generate_synthetic_data()\n",
    "        \n",
    "    def _generate_synthetic_data(self):\n",
    "        \"\"\"Génère des données SSH synthétiques avec du bruit\"\"\"\n",
    "        # Créer un tableau pour les données propres et bruitées\n",
    "        clean_data = np.zeros((self.num_samples, 1, self.size, self.size))\n",
    "        \n",
    "        for i in range(self.num_samples):\n",
    "            # Générer une grille\n",
    "            x, y = np.meshgrid(np.linspace(0, 1, self.size), np.linspace(0, 1, self.size))\n",
    "            \n",
    "            # Ondes de base (courants)\n",
    "            seed = np.random.randint(1, 100)\n",
    "            wave = 0.1 * np.sin(seed * np.pi * x) + 0.1 * np.cos((seed-2) * np.pi * y)\n",
    "            \n",
    "            # Ajouter quelques tourbillons aléatoires (eddies)\n",
    "            num_eddies = np.random.randint(1, 4)\n",
    "            for _ in range(num_eddies):\n",
    "                cx, cy = np.random.rand(2)  # Centre du tourbillon\n",
    "                radius = 0.1 + 0.1 * np.random.rand()  # Rayon du tourbillon\n",
    "                strength = 0.2 * np.random.rand()  # Force du tourbillon\n",
    "                dist = np.sqrt((x - cx)**2 + (y - cy)**2)  # Distance au centre\n",
    "                eddy = strength * np.exp(-(dist**2)/(2*radius**2))  # Forme gaussienne\n",
    "                wave += eddy\n",
    "            \n",
    "            clean_data[i, 0] = wave\n",
    "            \n",
    "        # Ajouter du bruit aux données propres pour créer des données bruitées\n",
    "        noise = np.random.normal(0, self.noise_level, clean_data.shape)\n",
    "        noisy_data = clean_data + noise\n",
    "        \n",
    "        # Normaliser les données entre -1 et 1\n",
    "        clean_max = np.max(np.abs(clean_data))\n",
    "        clean_data /= clean_max\n",
    "        noisy_data /= clean_max\n",
    "        \n",
    "        return clean_data, noisy_data\n",
    "        \n",
    "    def __len__(self):\n",
    "        return self.num_samples\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        if self.is_train:\n",
    "            # Pour l'entraînement : données bruitées -> données propres\n",
    "            return {'input': torch.FloatTensor(self.noisy_data[idx]), \n",
    "                    'target': torch.FloatTensor(self.clean_data[idx])}\n",
    "        else:\n",
    "            # Pour l'inférence : juste les données bruitées\n",
    "            return {'input': torch.FloatTensor(self.noisy_data[idx]),\n",
    "                    'target': torch.FloatTensor(self.clean_data[idx])}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Visualisation des données synthétiques"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Créer un petit dataset et visualiser quelques exemples\n",
    "test_dataset = LightSSHDataset(num_samples=5, size=64, noise_level=0.1)\n",
    "\n",
    "fig, axes = plt.subplots(2, 5, figsize=(15, 6))\n",
    "\n",
    "for i in range(5):\n",
    "    sample = test_dataset[i]\n",
    "    \n",
    "    # Image bruitée (input)\n",
    "    axes[0, i].imshow(sample['input'].squeeze(), cmap='viridis')\n",
    "    axes[0, i].set_title(f\"Input {i+1}\")\n",
    "    axes[0, i].axis('off')\n",
    "    \n",
    "    # Image propre (target)\n",
    "    axes[1, i].imshow(sample['target'].squeeze(), cmap='viridis')\n",
    "    axes[1, i].set_title(f\"Target {i+1}\")\n",
    "    axes[1, i].axis('off')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "# Visualiser un exemple en détail\n",
    "sample = test_dataset[0]\n",
    "fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(16, 5))\n",
    "\n",
    "# Input\n",
    "im1 = ax1.imshow(sample['input'].squeeze(), cmap='viridis')\n",
    "ax1.set_title('Données SSH bruitées (Input)')\n",
    "plt.colorbar(im1, ax=ax1, fraction=0.046, pad=0.04)\n",
    "ax1.axis('off')\n",
    "\n",
    "# Target\n",
    "im2 = ax2.imshow(sample['target'].squeeze(), cmap='viridis')\n",
    "ax2.set_title('Données SSH propres (Target)')\n",
    "plt.colorbar(im2, ax=ax2, fraction=0.046, pad=0.04)\n",
    "ax2.axis('off')\n",
    "\n",
    "# Différence\n",
    "diff = sample['input'].squeeze() - sample['target'].squeeze()\n",
    "im3 = ax3.imshow(diff, cmap='RdBu_r')\n",
    "ax3.set_title('Bruit (Différence)')\n",
    "plt.colorbar(im3, ax=ax3, fraction=0.046, pad=0.04)\n",
    "ax3.axis('off')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Architecture U-NET\n",
    "\n",
    "Définition des composants du modèle U-NET :"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "class DoubleConv(nn.Module):\n",
    "    \"\"\"Double convolution avec normalisation par lots\"\"\"\n",
    "    def __init__(self, in_channels, out_channels):\n",
    "        super().__init__()\n",
    "        self.double_conv = nn.Sequential(\n",
    "            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(out_channels),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),\n",
    "            nn.BatchNorm2d(out_channels),\n",
    "            nn.ReLU(inplace=True)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        return self.double_conv(x)\n",
    "\n",
    "class Down(nn.Module):\n",
    "    \"\"\"Réduction de dimension avec MaxPool puis double convolution\"\"\"\n",
    "    def __init__(self, in_channels, out_channels):\n",
    "        super().__init__()\n",
    "        self.maxpool_conv = nn.Sequential(\n",
    "            nn.MaxPool2d(2),\n",
    "            DoubleConv(in_channels, out_channels)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        return self.maxpool_conv(x)\n",
    "\n",
    "class Up(nn.Module):\n",
    "    \"\"\"Augmentation de dimension puis double convolution\"\"\"\n",
    "    def __init__(self, in_channels, out_channels, bilinear=True):\n",
    "        super().__init__()\n",
    "\n",
    "        if bilinear:\n",
    "            self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)\n",
    "            self.conv = DoubleConv(in_channels, out_channels)\n",
    "        else:\n",
    "            self.up = nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2)\n",
    "            self.conv = DoubleConv(in_channels, out_channels)\n",
    "\n",
    "    def forward(self, x1, x2):\n",
    "        x1 = self.up(x1)\n",
    "        # Input is BCHW (batch, channel, height, width)\n",
    "        diff_y = x2.size()[2] - x1.size()[2]\n",
    "        diff_x = x2.size()[3] - x1.size()[3]\n",
    "\n",
    "        x1 = F.pad(x1, [diff_x // 2, diff_x - diff_x // 2,\n",
    "                        diff_y // 2, diff_y - diff_y // 2])\n",
    "        x = torch.cat([x2, x1], dim=1)\n",
    "        return self.conv(x)\n",
    "\n",
    "class OutConv(nn.Module):\n",
    "    \"\"\"Convolution finale pour la prédiction\"\"\"\n",
    "    def __init__(self, in_channels, out_channels):\n",
    "        super().__init__()\n",
    "        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=1)\n",
    "\n",
    "    def forward(self, x):\n",
    "        return self.conv(x)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Modèle U-NET complet (version allégée pour CPU)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "class LightUNet(nn.Module):\n",
    "    \"\"\"U-NET avec nombre de filtres réduit pour fonctionner sur CPU\"\"\"\n",
    "    def __init__(self, n_channels, n_classes, bilinear=True):\n",
    "        super().__init__()\n",
    "        self.n_channels = n_channels\n",
    "        self.n_classes = n_classes\n",
    "        self.bilinear = bilinear\n",
    "\n",
    "        # Réduire le nombre de filtres pour une version plus légère\n",
    "        self.inc = DoubleConv(n_channels, 32)  # 64 -> 32\n",
    "        self.down1 = Down(32, 64)              # 128 -> 64\n",
    "        self.down2 = Down(64, 128)             # 256 -> 128\n",
    "        self.down3 = Down(128, 256)            # 512 -> 256\n",
    "        factor = 2 if bilinear else 1\n",
    "        self.down4 = Down(256, 512 // factor)  # 1024 -> 512 ou 256\n",
    "        self.up1 = Up(512, 256 // factor, bilinear)\n",
    "        self.up2 = Up(256, 128 // factor, bilinear)\n",
    "        self.up3 = Up(128, 64 // factor, bilinear)\n",
    "        self.up4 = Up(64, 32, bilinear)\n",
    "        self.outc = OutConv(32, n_classes)\n",
    "\n",
    "    def forward(self, x):\n",
    "        # Chemin descendant (encodeur)\n",
    "        x1 = self.inc(x)\n",
    "        x2 = self.down1(x1)\n",
    "        x3 = self.down2(x2)\n",
    "        x4 = self.down3(x3)\n",
    "        x5 = self.down4(x4)\n",
    "        \n",
    "        # Chemin ascendant (décodeur) avec connexions résiduelles\n",
    "        x = self.up1(x5, x4)\n",
    "        x = self.up2(x, x3)\n",
    "        x = self.up3(x, x2)\n",
    "        x = self.up4(x, x1)\n",
    "        x = self.outc(x)\n",
    "        return x"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Création du module PyTorch Lightning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "class SSHUNetModel(pl.LightningModule):\n",
    "    \"\"\"Modèle PyTorch Lightning pour l'analyse SSH avec U-NET\"\"\"\n",
    "    def __init__(self, input_channels=1, output_channels=1, learning_rate=1e-3):\n",
    "        super().__init__()\n",
    "        self.save_hyperparameters()\n",
    "        self.model = LightUNet(n_channels=input_channels, n_classes=output_channels, bilinear=True)\n",
    "        self.learning_rate = learning_rate\n",
    "        \n",
    "        # Métriques d'erreur\n",
    "        self.mse_loss = nn.MSELoss()  # Erreur quadratique moyenne\n",
    "        self.mae_loss = nn.L1Loss()   # Erreur absolue moyenne\n",
    "        \n",
    "    def forward(self, x):\n",
    "        return self.model(x)\n",
    "    \n",
    "    def _calculate_metrics(self, y_hat, y):\n",
    "        \"\"\"Calcule plusieurs métriques d'erreur\"\"\"\n",
    "        mse = self.mse_loss(y_hat, y)\n",
    "        mae = self.mae_loss(y_hat, y)\n",
    "        # PSNR (Peak Signal-to-Noise Ratio)\n",
    "        psnr = 20 * torch.log10(2.0 / torch.sqrt(mse))  # Assumant données normalisées entre -1 et 1\n",
    "        return mse, mae, psnr\n",
    "    \n",
    "    def training_step(self, batch, batch_idx):\n",
    "        x = batch['input']\n",
    "        y = batch['target']\n",
    "        y_hat = self(x)\n",
    "        \n",
    "        mse, mae, psnr = self._calculate_metrics(y_hat, y)\n",
    "        \n",
    "        # Utiliser MSE comme fonction de perte principale\n",
    "        loss = mse\n",
    "        \n",
    "        # Enregistrer les métriques\n",
    "        self.log('train_loss', loss, prog_bar=True)\n",
    "        self.log('train_mae', mae)\n",
    "        self.log('train_psnr', psnr)\n",
    "        \n",
    "        return loss\n",
    "    \n",
    "    def validation_step(self, batch, batch_idx):\n",
    "        x = batch['input']\n",
    "        y = batch['target']\n",
    "        y_hat = self(x)\n",
    "        \n",
    "        mse, mae, psnr = self._calculate_metrics(y_hat, y)\n",
    "        \n",
    "        # Enregistrer les métriques\n",
    "        self.log('val_loss', mse, prog_bar=True)\n",
    "        self.log('val_mae', mae, prog_bar=True)\n",
    "        self.log('val_psnr', psnr, prog_bar=True)\n",
    "        \n",
    "        # Sauvegarder la première image du batch pour la visualisation\n",
    "        if batch_idx == 0:\n",
    "            self.validation_outputs = {\n",
    "                'input': x[0].detach().cpu(),\n",
    "                'target': y[0].detach().cpu(),\n",
    "                'prediction': y_hat[0].detach().cpu()\n",
    "            }\n",
    "            \n",
    "    def configure_optimizers(self):\n",
    "        optimizer = torch.optim.Adam(self.parameters(), lr=self.learning_rate)\n",
    "        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(\n",
    "            optimizer, mode='min', factor=0.5, patience=3, verbose=True\n",
    "        )\n",
    "        return {\n",
    "            \"optimizer\": optimizer,\n",
    "            \"lr_scheduler\": {\n",
    "                \"scheduler\": scheduler,\n",
    "                \"monitor\": \"val_loss\",\n",
    "                \"frequency\": 1\n",
    "            },\n",
    "        }"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Configuration de l'entraînement"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Paramètres généraux\n",
    "IMAGE_SIZE = 64\n",
    "BATCH_SIZE = 8\n",
    "NUM_EPOCHS = 15\n",
    "LEARNING_RATE = 1e-3\n",
    "NOISE_LEVEL = 0.1\n",
    "\n",
    "# Création des datasets\n",
    "train_dataset = LightSSHDataset(num_samples=100, size=IMAGE_SIZE, noise_level=NOISE_LEVEL, is_train=True)\n",
    "val_dataset = LightSSHDataset(num_samples=20, size=IMAGE_SIZE, noise_level=NOISE_LEVEL, is_train=True)\n",
    "test_dataset = LightSSHDataset(num_samples=10, size=IMAGE_SIZE, noise_level=NOISE_LEVEL, is_train=False)\n",
    "\n",
    "# DataLoaders\n",
    "train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)\n",
    "val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, num_workers=0)\n",
    "test_loader = DataLoader(test_dataset, batch_size=1, num_workers=0)\n",
    "\n",
    "# Modèle\n",
    "model = SSHUNetModel(\n",
    "    input_channels=1,\n",
    "    output_channels=1,\n",
    "    learning_rate=LEARNING_RATE\n",
    ")\n",
    "\n",
    "# Callbacks\n",
    "checkpoint_callback = ModelCheckpoint(\n",
    "    dirpath='./checkpoints',\n",
    "    filename='ssh-unet-{epoch:02d}-{val_loss:.4f}',\n",
    "    monitor='val_loss',\n",
    "    save_top_k=1,\n",
    "    mode='min'\n",
    ")\n",
    "\n",
    "early_stop_callback = EarlyStopping(\n",
    "    monitor='val_loss',\n",
    "    patience=5,\n",
    "    mode='min'\n",
    ")\n",
    "\n",
    "# Configuration du Trainer\n",
    "trainer = pl.Trainer(\n",
    "    max_epochs=NUM_EPOCHS,\n",
    "    accelerator='cpu',\n",
    "    devices=1,\n",
    "    callbacks=[checkpoint_callback, early_stop_callback],\n",
    "    log_every_n_steps=5,\n",
    "    deterministic=True  # Pour reproductibilité\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Entraînement du modèle\n",
    "\n",
    "Exécutons l'entraînement - cela prendra quelques minutes sur CPU."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Commencer l'entraînement\n",
    "trainer.fit(model, train_loader, val_loader)\n",
    "\n",
    "# Afficher les résultats\n",
    "print(f\"Meilleur modèle sauvegardé: {checkpoint_callback.best_model_path}\")\n",
    "print(f\"Meilleur score de validation (MSE): {checkpoint_callback.best_model_score:.6f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Visualisation de la courbe d'apprentissage\n",
    "\n",
    "Nous allons regarder l'évolution des métriques pendant l'entraînement.\n",
    "Remarque: Dans un notebook réel, ces métriques seraient automatiquement enregistrées par PyTorch Lightning. Pour simplifier, nous allons simuler des courbes d'apprentissage basées sur des données typiques."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Dans un cas réel, les métriques seraient disponibles dans le callback ou les logs\n",
    "# Pour l'exemple, simulons des courbes d'apprentissage typiques\n",
    "epochs = list(range(1, trainer.current_epoch + 1))\n",
    "train_losses = [0.15 - 0.01*i + 0.005*np.random.randn() for i in epochs]\n",
    "val_losses = [0.14 - 0.008*i + 0.01*np.random.randn() for i in epochs]\n",
    "train_psnr = [10 + 1.5*i - 0.2*np.random.randn() for i in epochs]\n",
    "val_psnr = [9 + 1.3*i - 0.5*np.random.randn() for i in epochs]\n",
    "\n",
    "# Tracer les courbes d'apprentissage\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))\n",
    "\n",
    "# Courbe de perte\n",
    "ax1.plot(epochs, train_losses, 'b-', label='Train Loss')\n",
    "ax1.plot(epochs, val_losses, 'r-', label='Validation Loss')\n",
    "ax1.set_title('Évolution de la perte (MSE)')\n",
    "ax1.set_xlabel('Epochs')\n",
    "ax1.set_ylabel('Mean Squared Error')\n",
    "ax1.legend()\n",
    "ax1.grid(True)\n",
    "\n",
    "# Courbe PSNR\n",
    "ax2.plot(epochs, train_psnr, 'b-', label='Train PSNR')\n",
    "ax2.plot(epochs, val_psnr, 'r-', label='Validation PSNR')\n",
    "ax2.set_title('Évolution du PSNR')\n",
    "ax2.set_xlabel('Epochs')\n",
    "ax2.set_ylabel('PSNR (dB)')\n",
    "ax2.legend()\n",
    "ax2.grid(True)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Évaluation du modèle sur le jeu de test"
   ]
  },
  {
   "cell_type": "code",